[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "ezanchor"
dynamic = ["version"]
authors = [
  { name="wcfrobert", email="temprobertdev@gmail.com" },
]
description = "Nonstructural Component Anchorage Calculation"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.24.3",
    "matplotlib>=3.7.1",
]
keywords = [
    "structural engineering",
    "nonstructural",
    "anchorage",
    "seismic force"
]


[tool.hatch.version]
path = "ezanchor/__init__.py"


[project.urls]
"Homepage" = "https://github.com/wcfrobert/ezanchor"
"Bug Tracker" = "https://github.com/wcfrobert/ezanchor/issues"